<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Fanparking | Parked Vehicles</title>
    <link href="//fonts.googleapis.com/css?family=Lato:300" rel="stylesheet" type="text/css" />
    <style>
        /* Your custom styles here */
    </style>
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="/assets/js/helpers.js"></script>
</head>

<body>
    <main class="flex w-full min-h-screen ">
        <nav class="flex flex-col items-center w-4/12">
            <section class="flex flex-col items-center space-y-2 w-full bg-teal-600 py-12">
                <div class="flex items-center bg-white rounded-full overflow-hidden p-3">
                    <img class="h-28 w-28 rounded-full" src="/assets/images/avatar.png" alt="">
                </div>
                <h1 class="text-3xl font-semibold text-white"><?= htmlspecialchars($auth['name']) ?></h1>
            </section>
            <div class="border"></div>
            <section class="flex flex-col w-full bg-teal-600 p-4">
                <ul class="flex flex-col w-full space-y-4">
                    <li>
                        <a class="text-2xl font-semibold text-white" href="/parked-vehicles">
                            Parked Vehicles
                        </a>
                    </li>
                    <?php if (\Stringy\Stringy::create($auth['email'] ?? '')->contains('admin')) : ?>
                        <li>
                            <a class="text-2xl font-semibold text-white" href="/users">
                                Users
                            </a>
                        </li>
                    <?php endif; ?>
                </ul>
            </section>
            <div class="border"></div>
            <section class="flex flex-col w-full h-full bg-teal-600 p-4">
                <form class="" method="POST" action="/users/handle-logout" enctype="multipart/form-data">
                    <button type="submit" class="text-2xl font-semibold text-white">
                        Logout
                    </button>
                </form>
            </section>
        </nav>

        <main class="bg-white flex-col w-8/12 space-y-4 p-6">
            <div class="flex flex-row justify-between">
                <h1 class="text-3xl font-semibold text-black">Parked Vehicles</h1>
                <a href="/parked-vehicles//enter" class="bg-teal-600 hover:bg-teal-700 text-white font-bold py-2 px-4 rounded">
                    Enter Vehicle
                </a>
            </div>

            <form class="flex flex-row space-x-4" method="" action="">
                <div class="w-full">
                    <label for="keyword" class="block text-sm font-semibold">Search</label>
                    <input type="text" id="keyword" name="keyword" class="w-full p-2 border rounded-lg border-gray-400 focus:outline-gray-600 bg-gray-300/25" value="<?= htmlspecialchars($pagination['keyword'] ?? '') ?>" placeholder="Plate number">
                </div>
                <div class="mt-auto">
                    <button type="submit" class="block bg-teal-600 hover:bg-teal-700 text-white font-bold py-2 px-4 rounded">
                        Search
                    </button>
                </div>
            </form>

            <?php if (
                (isset($status_code) && isset($message)) &&
                in_array($status_code, array_merge(range(200, 299), [404, 422]))
            ) : ?>
                <div id="messageContainer" class="col-span-2 p-1 border rounded flex justify-between 
                        <?= in_array($status_code, range(200, 299)) ? 'border-green-400 bg-green-300/25 text-green-500' : 'border-red-400 bg-red-300/25 text-red-500' ?>">
                    <div>
                        <span class=""><?= in_array($status_code, range(200, 299)) ? '&#10003;' : '&#9888;' ?></span>
                        <small class="font-semibold text-xs">
                            <?= htmlspecialchars($message); ?>
                        </small>
                    </div>
                    <div class="">
                        <button id="messageContainerCloseBtn" type="button"><span class="">&#10005;</span></button>
                    </div>
                </div>
            <?php endif; ?>

            <div class="overflow-x-auto">
                <table class="min-w-full bg-white border border-gray-300 rounded">
                    <thead>
                        <tr>
                            <th class="text-nowrap py-2 px-4 border-b">Id</th>
                            <th class="text-nowrap py-2 px-4 border-b">Vehicle id</th>
                            <th class="text-nowrap py-2 px-4 border-b">Plate number</th>
                            <th class="text-nowrap py-2 px-4 border-b">Entered by user id</th>
                            <th class="text-nowrap py-2 px-4 border-b">Entered at</th>
                            <th class="text-nowrap py-2 px-4 border-b">Left by user id</th>
                            <th class="text-nowrap py-2 px-4 border-b">Left at</th>
                            <th class="text-nowrap py-2 px-4 border-b">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($pagination['data'] as $pv) { ?>
                            <tr>
                                <td class="text-nowrap py-2 px-4 border-b"><?= $pv['id']; ?></td>
                                <td class="text-nowrap py-2 px-4 border-b">
                                    <a class="block w-full h-full" href="/vehicles/<?= $pv['vehicle_id']; ?>"><?= $pv['vehicle_id']; ?></a>
                                </td>
                                <td class="text-nowrap py-2 px-4 border-b"><?= $pv['plate_number']; ?></td>
                                <td class="text-nowrap py-2 px-4 border-b">
                                    <a class="block w-full h-full" href="/users/<?= $pv['entered_by_user_id']; ?>"><?= $pv['entered_by_user_id']; ?></a>
                                </td>
                                <td class="text-nowrap py-2 px-4 border-b"><?= $pv['entered_at'] ?? '-'; ?></td>
                                <td class="text-nowrap py-2 px-4 border-b">
                                    <a class="block w-full h-full" href="/users/<?= $pv['left_by_user_id']; ?>"><?= $pv['left_by_user_id'] ?? '-'; ?></a>
                                </td>
                                <td class="text-nowrap py-2 px-4 border-b"><?= $pv['left_at'] ?? '-'; ?></td>
                                <td class="text-nowrap flex py-2 px-4 border-b">
                                    <a href="/parked-vehicles/<?= $pv['id'] ?>/toggle-left" class="border border-blue-500 text-blue-500 hover:bg-blue-500 hover:text-white py-2 px-4 rounded-md transition duration-300 ease-in-out">
                                        Toogle Left
                                    </a>
                                </td>
                            </tr>
                        <?php } ?>
                    </tbody>
                </table>

            </div>

            <div class="flex">
                <div class="flex ml-auto space-x-4">
                    <a href="<?= htmlspecialchars($pagination['prev_url']) ?>" class="bg-teal-600 hover:bg-teal-700 text-white font-bold py-2 px-4 rounded">
                        Prev
                    </a>
                    <a href="<?= htmlspecialchars($pagination['next_url']) ?>" class="bg-teal-600 hover:bg-teal-700 text-white font-bold py-2 px-4 rounded">
                        Next
                    </a>
                </div>
            </div>
        </main>
    </main>

    <script>
        document.addEventListener("DOMContentLoaded", function() {
            (document.getElementById("messageContainerCloseBtn")).addEventListener("click", function() {
                document.getElementById('messageContainer').remove();
            });

        });
    </script>
</body>

</html>