<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Fanparking | Dashboard</title>
    <link href="//fonts.googleapis.com/css?family=Lato:300" rel="stylesheet" type="text/css" />
    <style>
        /* Your custom styles here */
    </style>
    <script src="https://cdn.tailwindcss.com"></script>
</head>

<body>
    <h1 class="text-8xl">Dashboard</h1>
</body>

</html>