<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Fanparking | Dashboard</title>
    <link href="//fonts.googleapis.com/css?family=Lato:300" rel="stylesheet" type="text/css" />
    <style>
        /* Your custom styles here */
    </style>
    <script src="https://cdn.tailwindcss.com"></script>
    <script src="/assets/js/helpers.js"></script>
</head>

<body>
    <main class="flex w-full min-h-screen ">
        <nav class="flex flex-col items-center w-4/12">
            <section class="flex flex-col items-center space-y-2 w-full bg-teal-600 py-12">
                <div class="flex items-center bg-white rounded-full overflow-hidden p-3">
                    <img class="h-28 w-28 rounded-full" src="/assets/images/avatar.png" alt="">
                </div>
                <h1 class="text-3xl font-semibold text-white"><?= htmlspecialchars($auth['name']) ?></h1>
            </section>
            <div class="border"></div>
            <section class="flex flex-col w-full bg-teal-600 p-4">
                <ul class="flex flex-col w-full space-y-4">
                    <li>
                        <a class="text-2xl font-semibold text-white" href="/parked-vehicles">
                            Parked Vehicles
                        </a>
                    </li>
                    <?php if (\Stringy\Stringy::create($auth['email'] ?? '')->contains('admin')) : ?>
                        <li>
                            <a class="text-2xl font-semibold text-white" href="/users">
                                Users
                            </a>
                        </li>
                    <?php endif; ?>
                </ul>
            </section>
            <div class="border"></div>
            <section class="flex flex-col w-full h-full bg-teal-600 p-4">
                <form class="" method="POST" action="/users/handle-logout" enctype="multipart/form-data">
                    <button type="submit" class="text-2xl font-semibold text-white">
                        Logout
                    </button>
                </form>
            </section>
        </nav>

        <main class="bg-white flex-col w-8/12 space-y-4 p-6">
            <div class="flex flex-row justify-between">
                <h1 class="text-3xl font-semibold text-black">Users</h1>
                <a href="/users//create" class="bg-teal-600 hover:bg-teal-700 text-white font-bold py-2 px-4 rounded">
                    Create
                </a>
            </div>

            <form class="flex flex-row space-x-4" method="" action="">
                <div class="w-full">
                    <label for="keyword" class="block text-sm font-semibold">Search</label>
                    <input type="text" id="keyword" name="keyword" class="w-full p-2 border rounded-lg border-gray-400 focus:outline-gray-600 bg-gray-300/25" value="<?= htmlspecialchars($pagination['keyword'] ?? '') ?>" placeholder="Name or email">
                </div>
                <div class="mt-auto">
                    <button type="submit" class="block bg-teal-600 hover:bg-teal-700 text-white font-bold py-2 px-4 rounded">
                        Search
                    </button>
                </div>
            </form>

            <?php if (
                (isset($status_code) && isset($message)) &&
                in_array($status_code, array_merge(range(200, 299), [404, 422]))
            ) : ?>
                <div id="messageContainer" class="col-span-2 p-1 border rounded flex justify-between 
                        <?= in_array($status_code, range(200, 299)) ? 'border-green-400 bg-green-300/25 text-green-500' : 'border-red-400 bg-red-300/25 text-red-500' ?>">
                    <div>
                        <span class=""><?= in_array($status_code, range(200, 299)) ? '&#10003;' : '&#9888;' ?></span>
                        <small class="font-semibold text-xs">
                            <?= htmlspecialchars($message); ?>
                        </small>
                    </div>
                    <div class="">
                        <button id="messageContainerCloseBtn" type="button"><span class="">&#10005;</span></button>
                    </div>
                </div>
            <?php endif; ?>

            <div class="overflow-x-auto">
                <table class="min-w-full bg-white border border-gray-300 rounded">
                    <thead>
                        <tr>
                            <th class="text-nowrap py-2 px-4 border-b">Id</th>
                            <th class="text-nowrap py-2 px-4 border-b">Name</th>
                            <th class="text-nowrap py-2 px-4 border-b">Email</th>
                            <th class="text-nowrap py-2 px-4 border-b">Created at</th>
                            <th class="text-nowrap py-2 px-4 border-b">Updated at</th>
                            <th class="text-nowrap py-2 px-4 border-b">Deactivated at</th>
                            <th class="text-nowrap py-2 px-4 border-b">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($pagination['data'] as $user) { ?>
                            <tr>
                                <td class="text-nowrap py-2 px-4 border-b"><?= $user['id']; ?></td>
                                <td class="text-nowrap py-2 px-4 border-b"><?= $user['name']; ?></td>
                                <td class="text-nowrap py-2 px-4 border-b"><?= $user['email']; ?></td>
                                <td class="text-nowrap py-2 px-4 border-b"><?= $user['created_at']; ?></td>
                                <td class="text-nowrap py-2 px-4 border-b"><?= $user['updated_at'] ?? '-'; ?></td>
                                <td class="text-nowrap py-2 px-4 border-b"><?= $user['deactived_at'] ?? '-'; ?></td>
                                <td class="flex py-2 px-4 border-b">
                                    <a href="/users/<?= $user['id'] ?>/edit" class="border border-blue-500 text-blue-500 hover:bg-blue-500 hover:text-white py-2 px-4 rounded-md transition duration-300 ease-in-out">
                                        Edit
                                    </a>
                                </td>
                            </tr>
                        <?php } ?>
                    </tbody>
                </table>

            </div>

            <div class="flex">
                <div class="flex ml-auto space-x-4">
                    <a href="<?= htmlspecialchars($pagination['prev_url']) ?>" class="bg-teal-600 hover:bg-teal-700 text-white font-bold py-2 px-4 rounded">
                        Prev
                    </a>
                    <a href="<?= htmlspecialchars($pagination['next_url']) ?>" class="bg-teal-600 hover:bg-teal-700 text-white font-bold py-2 px-4 rounded">
                        Next
                    </a>
                </div>
            </div>
        </main>
    </main>

    <script>
        document.addEventListener("DOMContentLoaded", function() {
            (document.getElementById("messageContainerCloseBtn")).addEventListener("click", function() {
                document.getElementById('messageContainer').remove();
            });

        });
    </script>

    <!-- <script>
        document.addEventListener('DOMContentLoaded', function() {
            const deleteBtns = document.getElementsByClassName('delete-btn');
            for (let i = 0; i < deleteBtns.length; i++) {
                deleteBtns[i].addEventListener('click', async (event) => {
                    const user = JSON.parse(event.target.getAttribute('user'));
                    user.deactived_at = user.deactived_at == null ? formatDateToYYYYMMDDHHMMSS(new Date()) : null
                    const formData = new URLSearchParams();
                    for (let key in user) {
                        formData.append(key, user[key]);
                    }
                    const response = await fetch(`/users/${user.id}/handle-update`, {
                        method: 'PUT',
                        headers: {
                            'Content-Type': 'application/x-www-form-urlencoded',
                        },
                        body: formData,
                    })
                    console.log(response);
                    return
                    location.reload();
                })
            }
        });
    </script> -->
</body>

</html>